import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import type { Locale } from "@/i18n/routing";

export interface BlogFaqItem {
  q: string;
  a: string;
}

export interface BlogPostMeta {
  slug: string;
  title: string;
  description: string;
  date: string;
  updated?: string;
  image?: string;
  imageAlt?: string;
  tags: string[];
  faq: BlogFaqItem[];
}

export interface BlogPost extends BlogPostMeta {
  content: string;
}

const BLOG_DIR = path.join(process.cwd(), "content", "blog");
const COVERS_DIR = path.join(process.cwd(), "public", "blog", "covers");

// Covers are generated by scripts/generate-blog-covers.ps1 and picked up by
// naming convention (<locale>-<slug>.jpg), so a post needs no extra frontmatter.
// A post can still set its own `image` in frontmatter, which wins.
function coverFor(locale: Locale, slug: string): string | undefined {
  const file = `${locale}-${slug}.jpg`;
  return fs.existsSync(path.join(COVERS_DIR, file)) ? `/blog/covers/${file}` : undefined;
}

export function getAllPostSlugs(locale: Locale): string[] {
  const dir = path.join(BLOG_DIR, locale);
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((file) => file.endsWith(".mdx"))
    .map((file) => file.replace(/\.mdx$/, ""));
}

export function getPost(locale: Locale, slug: string): BlogPost | null {
  const filePath = path.join(BLOG_DIR, locale, `${slug}.mdx`);
  if (!fs.existsSync(filePath)) return null;

  const raw = fs.readFileSync(filePath, "utf8");
  const { data, content } = matter(raw);

  return {
    slug,
    title: data.title ?? slug,
    description: data.description ?? "",
    date: data.date ?? "",
    updated: data.updated,
    image: data.image ?? coverFor(locale, slug),
    imageAlt: data.imageAlt ?? data.title ?? slug,
    tags: data.tags ?? [],
    faq: Array.isArray(data.faq) ? data.faq : [],
    content,
  };
}

export function getAllPosts(locale: Locale): BlogPostMeta[] {
  return getAllPostSlugs(locale)
    .map((slug) => getPost(locale, slug))
    .filter((p): p is BlogPost => p !== null)
    .sort((a, b) => ((a.updated ?? a.date) < (b.updated ?? b.date) ? 1 : -1))
    .map((post) => ({
      slug: post.slug,
      title: post.title,
      description: post.description,
      date: post.date,
      updated: post.updated,
      image: post.image,
      imageAlt: post.imageAlt,
      tags: post.tags,
      faq: post.faq,
    }));
}

// Other posts ranked by how many tags they share with this one — used for the
// "related articles" block, which gives readers and crawlers a topical path
// from one article to the next instead of a dead end.
export function getRelatedPosts(
  locale: Locale,
  slug: string,
  tags: string[],
  limit = 3
): BlogPostMeta[] {
  return getAllPosts(locale)
    .filter((p) => p.slug !== slug)
    .map((p) => ({ post: p, score: p.tags.filter((t) => tags.includes(t)).length }))
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((x) => x.post);
}
